[phases.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build --filter=@vocilia/backend"]

[start]
cmd = "node apps/backend/dist/server.js"
