openapi: 3.0.3
info:
  title: AI Call Management API
  description: API for managing AI-powered customer feedback calls
  version: 1.0.0
  contact:
    name: Vocilia Development Team
    
servers:
  - url: https://api.vocilia.com/v1
    description: Production server
  - url: https://staging-api.vocilia.com/v1
    description: Staging server

paths:
  /ai/calls/initiate:
    post:
      summary: Initiate AI feedback call
      description: Start an AI-powered phone call for customer feedback collection (FR-001, FR-026)
      tags:
        - Call Management
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - customer_verification_id
                - phone_number
                - store_id
              properties:
                customer_verification_id:
                  type: string
                  format: uuid
                  description: Verified customer transaction ID
                phone_number:
                  type: string
                  pattern: '^\+46[0-9]{8,9}$'
                  description: Swedish phone number format
                store_id:
                  type: string
                  format: uuid
                  description: Store where customer transaction occurred
                priority:
                  type: string
                  enum: [normal, high]
                  default: normal
                  description: Call priority level
      responses:
        '202':
          description: Call initiation accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  call_session_id:
                    type: string
                    format: uuid
                  status:
                    type: string
                    enum: [pending, queued]
                  estimated_call_time:
                    type: string
                    description: ISO 8601 estimated call start time
                  retry_count:
                    type: integer
                    minimum: 0
                    maximum: 3
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Call already exists for this verification
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /ai/calls/{call_session_id}/status:
    get:
      summary: Get call session status
      description: Retrieve current status of an AI feedback call (FR-007)
      tags:
        - Call Management
      security:
        - BearerAuth: []
      parameters:
        - name: call_session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Call status retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  call_session_id:
                    type: string
                    format: uuid
                  status:
                    type: string
                    enum: [pending, in_progress, completed, failed, abandoned]
                  current_retry:
                    type: integer
                  duration_seconds:
                    type: integer
                    nullable: true
                  quality_metrics:
                    $ref: '#/components/schemas/CallQualityMetrics'
                  failure_reason:
                    type: string
                    nullable: true
        '404':
          description: Call session not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    patch:
      summary: Update call session
      description: Update call session status or metadata (FR-008)
      tags:
        - Call Management
      security:
        - BearerAuth: []
      parameters:
        - name: call_session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [abandoned, failed]
                failure_reason:
                  type: string
                  maxLength: 100
                end_reason:
                  type: string
                  enum: [customer_hangup, technical_failure, non_swedish, timeout]
      responses:
        '200':
          description: Call session updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  call_session_id:
                    type: string
                    format: uuid
                  status:
                    type: string
                  updated_at:
                    type: string
                    format: date-time
        '400':
          description: Invalid update request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /ai/calls/{call_session_id}/transcript:
    post:
      summary: Submit conversation transcript
      description: Submit AI conversation transcript for analysis (FR-006)
      tags:
        - Call Management
      security:
        - BearerAuth: []
      parameters:
        - name: call_session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - messages
                - total_duration_seconds
              properties:
                messages:
                  type: array
                  items:
                    $ref: '#/components/schemas/ConversationMessage'
                total_duration_seconds:
                  type: integer
                  minimum: 60
                  maximum: 120
                  description: Must be 1-2 minutes for successful analysis (FR-003)
                openai_session_id:
                  type: string
                  description: OpenAI Realtime API session identifier
                final_audio_quality:
                  $ref: '#/components/schemas/CallQualityMetrics'
      responses:
        '201':
          description: Transcript submitted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  transcript_id:
                    type: string
                    format: uuid
                  analysis_queued:
                    type: boolean
                  estimated_analysis_completion:
                    type: string
                    format: date-time
        '400':
          description: Invalid transcript data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /ai/calls/retry/{customer_verification_id}:
    post:
      summary: Retry failed call
      description: Attempt to retry a failed AI call (max 3 total attempts)
      tags:
        - Call Management
      security:
        - BearerAuth: []
      parameters:
        - name: customer_verification_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '202':
          description: Retry attempt accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  new_call_session_id:
                    type: string
                    format: uuid
                  retry_number:
                    type: integer
                    minimum: 1
                    maximum: 2
                  estimated_call_time:
                    type: string
                    format: date-time
        '409':
          description: Maximum retries exceeded (3 total attempts)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ConversationMessage:
      type: object
      required:
        - speaker
        - content
        - timestamp_ms
        - message_order
      properties:
        speaker:
          type: string
          enum: [ai, customer]
        content:
          type: string
          maxLength: 2000
          description: Spoken content
        timestamp_ms:
          type: integer
          description: Milliseconds from call start
        message_order:
          type: integer
          description: Sequence number in conversation
        confidence_score:
          type: number
          minimum: 0
          maximum: 1
          description: AI transcription confidence
        message_type:
          type: string
          enum: [question, response, system, error]
        language_detected:
          type: string
          default: 'sv'
          description: ISO 639-1 language code

    CallQualityMetrics:
      type: object
      properties:
        connection_quality:
          type: string
          enum: [excellent, good, fair, poor]
        audio_clarity_score:
          type: number
          minimum: 0
          maximum: 1
        latency_ms:
          type: integer
          description: Average response latency
        packet_loss_percentage:
          type: number
          minimum: 0
          maximum: 100
        openai_api_latency:
          type: integer
          description: AI response time in milliseconds

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          description: Additional error context
        timestamp:
          type: string
          format: date-time

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token from existing authentication system