openapi: 3.0.3
info:
  title: Feedback Analysis API
  description: API for AI-powered feedback analysis and quality grading
  version: 1.0.0
  contact:
    name: Vocilia Development Team

servers:
  - url: https://api.vocilia.com/v1
    description: Production server
  - url: https://staging-api.vocilia.com/v1
    description: Staging server

paths:
  /ai/analysis/process:
    post:
      summary: Process feedback for quality analysis
      description: Analyze completed conversation for quality, legitimacy, and reward calculation (FR-009, FR-010)
      tags:
        - Analysis
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - call_session_id
                - transcript_id
              properties:
                call_session_id:
                  type: string
                  format: uuid
                transcript_id:
                  type: string
                  format: uuid
                priority:
                  type: string
                  enum: [normal, high]
                  default: normal
      responses:
        '202':
          description: Analysis queued successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  analysis_id:
                    type: string
                    format: uuid
                  estimated_completion:
                    type: string
                    format: date-time
                  status:
                    type: string
                    enum: [queued, processing]
        '400':
          description: Invalid analysis request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Call session or transcript not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /ai/analysis/{analysis_id}/status:
    get:
      summary: Get analysis status
      description: Check the status of a feedback analysis job
      tags:
        - Analysis
      security:
        - BearerAuth: []
      parameters:
        - name: analysis_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Analysis status retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  analysis_id:
                    type: string
                    format: uuid
                  status:
                    type: string
                    enum: [queued, processing, completed, failed]
                  progress_percentage:
                    type: integer
                    minimum: 0
                    maximum: 100
                  current_stage:
                    type: string
                    enum: [legitimacy_check, depth_analysis, usefulness_analysis, scoring, summarization]
                  error_message:
                    type: string
                    nullable: true

  /ai/analysis/{analysis_id}/results:
    get:
      summary: Get analysis results
      description: Retrieve completed quality assessment and grading (FR-010, FR-011, FR-012, FR-013)
      tags:
        - Analysis
      security:
        - BearerAuth: []
      parameters:
        - name: analysis_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Analysis results retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QualityAssessment'
        '404':
          description: Analysis not found or not completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /ai/analysis/fraud-check:
    post:
      summary: Run fraud detection analysis
      description: Perform fraud detection on feedback content (FR-011, FR-016)
      tags:
        - Analysis
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - call_session_id
                - check_types
              properties:
                call_session_id:
                  type: string
                  format: uuid
                check_types:
                  type: array
                  items:
                    type: string
                    enum: [timing, content, context, pattern]
                  minItems: 1
                business_context:
                  type: object
                  description: Store context for validation
                force_recheck:
                  type: boolean
                  default: false
      responses:
        '200':
          description: Fraud detection completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  fraud_results:
                    type: array
                    items:
                      $ref: '#/components/schemas/FraudDetectionResult'
                  overall_is_fraudulent:
                    type: boolean
                  confidence_level:
                    type: number
                    minimum: 0
                    maximum: 1
                  should_exclude_from_rewards:
                    type: boolean

  /ai/analysis/summary/generate:
    post:
      summary: Generate feedback summary
      description: Create AI summary of high-quality feedback (FR-014)
      tags:
        - Analysis
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - call_session_id
                - quality_threshold
              properties:
                call_session_id:
                  type: string
                  format: uuid
                quality_threshold:
                  type: number
                  minimum: 0.02
                  maximum: 0.15
                  description: Minimum quality score for summarization
                preserve_details:
                  type: boolean
                  default: true
                  description: Preserve all key information in summary
                target_length:
                  type: string
                  enum: [brief, standard, detailed]
                  default: standard
      responses:
        '200':
          description: Summary generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary_id:
                    type: string
                    format: uuid
                  summary_text:
                    type: string
                    description: AI-generated feedback summary
                  key_insights:
                    type: array
                    items:
                      type: string
                  actionable_items:
                    type: array
                    items:
                      $ref: '#/components/schemas/ActionableItem'
                  summary_metadata:
                    type: object
                    description: Generation parameters and model info

  /ai/analysis/cleanup:
    delete:
      summary: Clean up low-grade feedback
      description: Delete feedback that doesn't qualify for rewards (FR-015)
      tags:
        - Analysis
      security:
        - BearerAuth: []
      parameters:
        - name: quality_threshold
          in: query
          required: true
          schema:
            type: number
            minimum: 0.02
            description: Delete feedback below this quality score
        - name: batch_size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            default: 100
        - name: dry_run
          in: query
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Cleanup completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  deleted_count:
                    type: integer
                  preserved_count:
                    type: integer
                  execution_time_ms:
                    type: integer
                  dry_run:
                    type: boolean

components:
  schemas:
    QualityAssessment:
      type: object
      required:
        - assessment_id
        - call_session_id
        - scores
        - reward_percentage
        - is_fraudulent
      properties:
        assessment_id:
          type: string
          format: uuid
        call_session_id:
          type: string
          format: uuid
        scores:
          type: object
          required:
            - legitimacy_score
            - depth_score
            - usefulness_score
            - overall_quality_score
          properties:
            legitimacy_score:
              type: number
              minimum: 0
              maximum: 1
              description: Fraud detection confidence (higher = more legitimate)
            depth_score:
              type: number
              minimum: 0
              maximum: 1
              description: Feedback detail level
            usefulness_score:
              type: number
              minimum: 0
              maximum: 1
              description: Actionable insights quality
            overall_quality_score:
              type: number
              minimum: 0
              maximum: 1
              description: Combined quality metric
        reward_percentage:
          type: number
          minimum: 2.00
          maximum: 15.00
          description: Cashback percentage (2-15% scale)
        is_fraudulent:
          type: boolean
          description: Automated fraud detection result
        fraud_reasons:
          type: array
          items:
            type: string
          description: Specific fraud indicators if detected
        analysis_summary:
          type: string
          nullable: true
          description: AI-generated feedback summary for qualifying content
        business_actionable_items:
          type: array
          items:
            $ref: '#/components/schemas/ActionableItem'
        analysis_metadata:
          type: object
          properties:
            model_version:
              type: string
            analysis_duration_ms:
              type: integer
            confidence_metrics:
              type: object
        created_at:
          type: string
          format: date-time

    FraudDetectionResult:
      type: object
      required:
        - check_type
        - is_suspicious
        - confidence_level
      properties:
        check_type:
          type: string
          enum: [timing, content, context, pattern]
        is_suspicious:
          type: boolean
        confidence_level:
          type: number
          minimum: 0
          maximum: 1
        fraud_indicators:
          type: array
          items:
            type: string
        context_violations:
          type: array
          items:
            type: object
            properties:
              violation_type:
                type: string
              expected_value:
                type: string
              actual_value:
                type: string
              severity:
                type: string
                enum: [low, medium, high, critical]
        decision_reasoning:
          type: string
          description: AI explanation for fraud determination

    ActionableItem:
      type: object
      required:
        - category
        - description
        - priority
      properties:
        category:
          type: string
          enum: [product, service, environment, staff, pricing, accessibility]
        description:
          type: string
          maxLength: 500
        priority:
          type: string
          enum: [low, medium, high, urgent]
        department:
          type: string
          nullable: true
          description: Specific store department if applicable
        estimated_impact:
          type: string
          enum: [minor, moderate, significant, major]
        implementation_complexity:
          type: string
          enum: [simple, moderate, complex]

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          description: Additional error context
        timestamp:
          type: string
          format: date-time

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token from existing authentication system